// playground/sveltekit/src/lib/locale-switcher.svelte
<script lang="ts">
  import { i18n } from '$lib/i18n'
  import { switchLocale } from 'best-i18n/client'
  import { locale } from 'best-i18n/svelte'

  const LABELS: Record<string, string> = {
    en: 'English',
    zh: '中文',
  }
</script>

<div>
  {#each i18n.locales as item (item)}
    <button
      type="button"
      aria-current={item === locale.current ? 'true' : undefined}
      disabled={item === locale.current}
      onclick={() => switchLocale(item, i18n)}
    >
      {LABELS[item] ?? item}
    </button>
  {/each}
</div>

// playground/tanstack-start/src/components/locale-switcher.tsx
import { switchLocale } from 'best-i18n/client'
import { useLocale } from 'best-i18n/react'

import { i18n } from '@/i18n'

const LABELS: Record<string, string> = {
  en: 'English',
  zh: '中文',
}

export function LocaleSwitcher() {
  const locale = useLocale()

  return (
    <div>
      {i18n.locales.map((item) => (
        <button
          key={item}
          type='button'
          aria-current={item === locale}
          disabled={item === locale}
          onClick={() => switchLocale(item, i18n)}
        >
          {LABELS[item] ?? item}
        </button>
      ))}
    </div>
  )
}
